<?php

namespace Database\Seeders;

use App\Models\Dish;
use Illuminate\Database\Seeder;

class DishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dishes = [
            // ==========================================
            // 1. ĐỒ ĂN (category_id = 1) - 12 món
            // ==========================================
            [
                'category_id' => 1,
                'dish_name' => 'Gà Rán Giòn Rụm (2 Miếng)',
                'image_url' => 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80',
                'price' => 38000.00,
                'description' => 'Gà tươi ướp gia vị đậm đà, chiên giòn tan vàng ươm bên ngoài mọng nước bên trong',
                'is_available' => true,
            ],
            [
                'category_id' => 1,
                'dish_name' => 'Gà Sốt Cay Hàn Quốc',
                'image_url' => 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=600&auto=format&fit=crop&q=80',
                'price' => 45000.00,
                'description' => 'Thịt gà giòn áo lớp sốt cay ngọt Gochujang đặc trưng rắc mè rang thơm lừng',
                'is_available' => true,
            ],
            [
                'category_id' => 1,
                'dish_name' => 'Gà Sốt Mật Ong Tỏi',
                'image_url' => 'https://images.unsplash.com/photo-1527477321005-4d01d75c2e55?w=600&auto=format&fit=crop&q=80',
                'price' => 45000.00,
                'description' => 'Gà chiên giòn quyện sốt mật ong rừng tự nhiên và tỏi phi béo ngậy',
                'is_available' => true,
            ],
            [
                'category_id' => 1,
                'dish_name' => 'Cánh Gà Chiên Nước Mắm (4 Miếng)',
                'image_url' => 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600&auto=format&fit=crop&q=80',
                'price' => 49000.00,
                'description' => 'Cánh gà chiên giòn thấm đẫm sốt nước mắm tỏi ớt mặn ngọt đưa cơm',
                'is_available' => true,
            ],
            [
                'category_id' => 1,
                'dish_name' => 'Khoai Tây Chiên Giòn Lắc Phô Mai',
                'image_url' => 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&auto=format&fit=crop&q=80',
                'price' => 28000.00,
                'description' => 'Khoai tây cọng Bỉ chiên vàng rụm lắc đẫm bột phô mai béo thơm',
                'is_available' => true,
            ],
            [
                'category_id' => 1,
                'dish_name' => 'Xúc Xích Đức Nướng Than',
                'image_url' => 'https://images.unsplash.com/photo-1585238342024-78d387f4a707?w=600&auto=format&fit=crop&q=80',
                'price' => 32000.00,
                'description' => 'Xúc xích thịt heo xông khói nướng than hoa thơm lừng kèm tương ớt xốt mù tạt',
                'is_available' => true,
            ],
            [
                'category_id' => 1,
                'dish_name' => 'Mẹt Xiên Que Cá Viên Chiên Thập Cẩm',
                'image_url' => 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80',
                'price' => 35000.00,
                'description' => 'Gồm cá viên, bò viên, tôm viên, xúc xích và đậu bắp chiên giòn chấm tương đen sốt cay',
                'is_available' => true,
            ],
            [
                'category_id' => 1,
                'dish_name' => 'Bò Lúc Lắc Khoai Tây Nghiền',
                'image_url' => 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
                'price' => 89000.00,
                'description' => 'Thịt thăn bò mềm xắt hạt lựu xào ớt chuông, hành tây sốt bơ tỏi ăn kèm khoai tây',
                'is_available' => true,
            ],
            [
                'category_id' => 1,
                'dish_name' => 'Bò Sốt Tiêu Đen Chảo Nóng',
                'image_url' => 'https://images.unsplash.com/photo-1558030006-450675393462?w=600&auto=format&fit=crop&q=80',
                'price' => 95000.00,
                'description' => 'Bò tươi mềm sốt tiêu đen Phú Quốc cay nồng đậm vị kèm bánh mì bơ tỏi',
                'is_available' => true,
            ],
            [
                'category_id' => 1,
                'dish_name' => 'Mực Xào Sa Tế Ớt Chuông',
                'image_url' => 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80',
                'price' => 79000.00,
                'description' => 'Mực ống tươi giòn xào cùng sa tế tôm cay thơm và rau củ quả tươi',
                'is_available' => true,
            ],
            [
                'category_id' => 1,
                'dish_name' => 'Cơm Chiên Dương Châu Thượng Hạng',
                'image_url' => 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&auto=format&fit=crop&q=80',
                'price' => 45000.00,
                'description' => 'Cơm chiên hạt tơi vàng ươm cùng lạp xưởng, tôm nõn, cà rốt và đậu Hà Lan',
                'is_available' => true,
            ],
            [
                'category_id' => 1,
                'dish_name' => 'Mì Xào Giòn Hải Sản Rau Củ',
                'image_url' => 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=600&auto=format&fit=crop&q=80',
                'price' => 55000.00,
                'description' => 'Sợi mì chiên phồng giòn rụm chan ngập sốt hải sản tôm mực rau củ đậm đà',
                'is_available' => true,
            ],

            // ==========================================
            // 2. ĐỒ UỐNG (category_id = 2) - 12 món
            // ==========================================
            [
                'category_id' => 2,
                'dish_name' => 'Trà Đào Cam Sả Tươi Mát',
                'image_url' => 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&auto=format&fit=crop&q=80',
                'price' => 32000.00,
                'description' => 'Hương trà thanh khiết kết hợp vị chua ngọt của đào miếng giòn và thơm dịu của cam sả',
                'is_available' => true,
            ],
            [
                'category_id' => 2,
                'dish_name' => 'Trà Chanh Mật Ong Giã Tay',
                'image_url' => 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
                'price' => 25000.00,
                'description' => 'Chanh tươi thơm lừng giã tay nguyên vỏ kết hợp trà ô long và mật ong ngọt thanh',
                'is_available' => true,
            ],
            [
                'category_id' => 2,
                'dish_name' => 'Trà Tắc Xí Muội Chua Ngọt',
                'image_url' => 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=600&auto=format&fit=crop&q=80',
                'price' => 22000.00,
                'description' => 'Nước cốt tắc tươi hòa cùng xí muội mặn ngọt mát lạnh sảng khoái',
                'is_available' => true,
            ],
            [
                'category_id' => 2,
                'dish_name' => 'Trà Sữa Trân Châu Đường Đen',
                'image_url' => 'https://images.unsplash.com/photo-1558857563-b371f30ca6a5?w=600&auto=format&fit=crop&q=80',
                'price' => 38000.00,
                'description' => 'Sữa tươi béo ngậy cùng trân châu nấu đường nâu dẻo mềm thơm phức',
                'is_available' => true,
            ],
            [
                'category_id' => 2,
                'dish_name' => 'Trà Sữa Matcha Kem Cheese',
                'image_url' => 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&auto=format&fit=crop&q=80',
                'price' => 42000.00,
                'description' => 'Matcha Nhật Bản thơm dịu phủ lớp kem cheese béo mặn sánh mịn',
                'is_available' => true,
            ],
            [
                'category_id' => 2,
                'dish_name' => 'Cà Phê Sữa Đá Sài Gòn Đậm Đà',
                'image_url' => 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=600&auto=format&fit=crop&q=80',
                'price' => 25000.00,
                'description' => 'Cà phê Robusta pha phin nguyên chất quyện sữa đặc thơm nồng truyền thống',
                'is_available' => true,
            ],
            [
                'category_id' => 2,
                'dish_name' => 'Cà Phê Đen Đá Pha Phin',
                'image_url' => 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&auto=format&fit=crop&q=80',
                'price' => 20000.00,
                'description' => 'Hương thơm quyến rũ, vị đắng thanh thuần khiết giúp tỉnh táo ngày dài',
                'is_available' => true,
            ],
            [
                'category_id' => 2,
                'dish_name' => 'Nước Ép Cam Tươi Nguyên Chất',
                'image_url' => 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80',
                'price' => 35000.00,
                'description' => '100% cam sành vắt tươi giàu Vitamin C không pha loãng',
                'is_available' => true,
            ],
            [
                'category_id' => 2,
                'dish_name' => 'Nước Ép Dưa Hấu Mát Lạnh',
                'image_url' => 'https://images.unsplash.com/photo-1589733955941-5eeaf752f6dd?w=600&auto=format&fit=crop&q=80',
                'price' => 30000.00,
                'description' => 'Dưa hấu tươi ép trực tiếp ngọt mát tự nhiên giúp giải nhiệt tức thì',
                'is_available' => true,
            ],
            [
                'category_id' => 2,
                'dish_name' => 'Sinh Tố Xoài Cát Béo Ngậy',
                'image_url' => 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=600&auto=format&fit=crop&q=80',
                'price' => 39000.00,
                'description' => 'Xoài cát chín mọng xay nhuyễn cùng sữa chua và đá tuyết thơm ngon',
                'is_available' => true,
            ],
            [
                'category_id' => 2,
                'dish_name' => 'Coca Cola Lon Ướp Lạnh (330ml)',
                'image_url' => 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80',
                'price' => 18000.00,
                'description' => 'Nước giải khát có gas sảng khoái mát lạnh kèm ly đá',
                'is_available' => true,
            ],
            [
                'category_id' => 2,
                'dish_name' => 'Pepsi Lon Ướp Lạnh (330ml)',
                'image_url' => 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
                'price' => 18000.00,
                'description' => 'Hương vị Pepsi cổ điển bùng nổ năng lượng mát lạnh',
                'is_available' => true,
            ],

            // ==========================================
            // 3. ĐỒ CHAY (category_id = 3) - 12 món
            // ==========================================
            [
                'category_id' => 3,
                'dish_name' => 'Cơm Chay Thập Cẩm Thanh Tịnh',
                'image_url' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop&q=80',
                'price' => 38000.00,
                'description' => 'Cơm dẻo ăn kèm sườn non chay, nấm kho tiêu, đậu hũ chiên sả và rau xào',
                'is_available' => true,
            ],
            [
                'category_id' => 3,
                'dish_name' => 'Cơm Chiên Nấm Hạt Sen Chay',
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
                'price' => 45000.00,
                'description' => 'Hạt cơm thơm chiên cùng hạt sen bùi ngậy, nấm hương, nấm đùi gà và cà rốt',
                'is_available' => true,
            ],
            [
                'category_id' => 3,
                'dish_name' => 'Mì Xào Giòn Rau Củ Nấm Chay',
                'image_url' => 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&auto=format&fit=crop&q=80',
                'price' => 42000.00,
                'description' => 'Mì chiên giòn sốt nấm bào ngư, nấm rơm, cải thìa và đậu hũ chiên thơm ngọt',
                'is_available' => true,
            ],
            [
                'category_id' => 3,
                'dish_name' => 'Bún Huế Chay Đậm Đà',
                'image_url' => 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80',
                'price' => 40000.00,
                'description' => 'Nước dùng nấu từ lê, táo, sả ớt thanh ngọt tự nhiên kèm chả huế chay, nấm rơm',
                'is_available' => true,
            ],
            [
                'category_id' => 3,
                'dish_name' => 'Phở Nấm Đông Cô Chay',
                'image_url' => 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&auto=format&fit=crop&q=80',
                'price' => 45000.00,
                'description' => 'Bánh phở mềm cùng nấm đông cô, bò lát chay, quẩy giòn và nước dùng thảo mộc',
                'is_available' => true,
            ],
            [
                'category_id' => 3,
                'dish_name' => 'Đậu Hũ Sốt Cà Chua Nấm Hương',
                'image_url' => 'https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?w=600&auto=format&fit=crop&q=80',
                'price' => 35000.00,
                'description' => 'Đậu hũ non mềm mịn chiên sơ sốt cà chua tươi đậm đà rắc hành ngò thơm',
                'is_available' => true,
            ],
            [
                'category_id' => 3,
                'dish_name' => 'Đậu Hũ Chiên Sả Ớt Giòn Cay',
                'image_url' => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
                'price' => 32000.00,
                'description' => 'Đậu hũ chiên vàng giòn phủ lớp sả ớt băm phi thơm cay nồng đưa cơm',
                'is_available' => true,
            ],
            [
                'category_id' => 3,
                'dish_name' => 'Rau Củ Luộc Chấm Kho Quẹt Chay',
                'image_url' => 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=600&auto=format&fit=crop&q=80',
                'price' => 45000.00,
                'description' => 'Đậu bắp, bông cải, cà rốt, khổ qua luộc xanh mướt chấm nồi kho quẹt nấm đậm đà',
                'is_available' => true,
            ],
            [
                'category_id' => 3,
                'dish_name' => 'Nấm Bào Ngư Xào Hạt Điều Béo Bùi',
                'image_url' => 'https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?w=600&auto=format&fit=crop&q=80',
                'price' => 55000.00,
                'description' => 'Nấm bào ngư tươi giòn ngọt xào cùng ớt chuông và hạt điều rang béo giòn',
                'is_available' => true,
            ],
            [
                'category_id' => 3,
                'dish_name' => 'Canh Rong Biển Hạt Sen Chay',
                'image_url' => 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop&q=80',
                'price' => 38000.00,
                'description' => 'Canh rong biển đậu hũ non hạt sen thanh lọc cơ thể ngọt thơm bổ dưỡng',
                'is_available' => true,
            ],
            [
                'category_id' => 3,
                'dish_name' => 'Gỏi Cuốn Ngũ Sắc Chay Chấm Tương Bơ',
                'image_url' => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
                'price' => 35000.00,
                'description' => 'Bánh tráng cuộn bún tươi, đậu hũ, nấm đùi gà, bơ sáp và rau thơm tươi mát',
                'is_available' => true,
            ],
            [
                'category_id' => 3,
                'dish_name' => 'Mẹt Bún Đậu Chả Cốm Chay',
                'image_url' => 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80',
                'price' => 45000.00,
                'description' => 'Đậu hũ chiên giòn, chả cốm chay, dồi chay chiên, bún lá và nước tương tắc ớt',
                'is_available' => true,
            ],

            // ==========================================
            // 4. BÁNH KEM (category_id = 4) - 11 món
            // ==========================================
            [
                'category_id' => 4,
                'dish_name' => 'Bánh Kem Dâu Tây Tươi (Size 16cm)',
                'image_url' => 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&auto=format&fit=crop&q=80',
                'price' => 280000.00,
                'description' => 'Cốt bông lan vani mềm mịn phủ kem tươi New Zealand và ngập tràn dâu tây Đà Lạt',
                'is_available' => true,
            ],
            [
                'category_id' => 4,
                'dish_name' => 'Bánh Kem Chocolate Truffle Bỉ',
                'image_url' => 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80',
                'price' => 320000.00,
                'description' => 'Hương vị socola đen 70% Bỉ đậm đà, vị đắng ngọt hài hòa phủ bột cacao cao cấp',
                'is_available' => true,
            ],
            [
                'category_id' => 4,
                'dish_name' => 'Bánh Kem Vani Trái Cây Tươi',
                'image_url' => 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=600&auto=format&fit=crop&q=80',
                'price' => 260000.00,
                'description' => 'Kem sữa tươi vani ngọt thanh kết hợp kiwi, xoài, nho đen và dâu tây căng mọng',
                'is_available' => true,
            ],
            [
                'category_id' => 4,
                'dish_name' => 'Bánh Kem Matcha Nhật Bản Uji',
                'image_url' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
                'price' => 290000.00,
                'description' => 'Bột trà xanh Uji Kyoto hảo hạng quyện kem phô mai béo ngậy ngọt dịu thanh tao',
                'is_available' => true,
            ],
            [
                'category_id' => 4,
                'dish_name' => 'Bánh Kem Red Velvet Nhung Đỏ',
                'image_url' => 'https://images.unsplash.com/photo-1586788680434-30d324b2d46f?w=600&auto=format&fit=crop&q=80',
                'price' => 310000.00,
                'description' => 'Cốt bánh đỏ nhung quý phái xen kẽ lớp kem cheese tươi chua nhẹ béo mịn',
                'is_available' => true,
            ],
            [
                'category_id' => 4,
                'dish_name' => 'Bánh Kem Tiramisu Ý Cao Cấp',
                'image_url' => 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&auto=format&fit=crop&q=80',
                'price' => 330000.00,
                'description' => 'Bánh ladyfinger thấm đẫm cà phê Espresso và rượu Kahlua quyện phô mai Mascarpone',
                'is_available' => true,
            ],
            [
                'category_id' => 4,
                'dish_name' => 'Bánh Kem Phô Mai New York Cheesecake',
                'image_url' => 'https://images.unsplash.com/photo-1524351199678-941a58a3df50?w=600&auto=format&fit=crop&q=80',
                'price' => 350000.00,
                'description' => 'Đậm đà phô mai cream cheese nướng vàng đế bánh quy giòn rụm thơm bơ',
                'is_available' => true,
            ],
            [
                'category_id' => 4,
                'dish_name' => 'Bánh Mousse Chanh Dây Mát Lạnh',
                'image_url' => 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600&auto=format&fit=crop&q=80',
                'price' => 240000.00,
                'description' => 'Mousse chanh dây mềm tan chua ngọt thanh nhiệt mùa hè cực kỳ cuốn hút',
                'is_available' => true,
            ],
            [
                'category_id' => 4,
                'dish_name' => 'Bánh Bông Lan Trứng Muối Sốt Phô Mai',
                'image_url' => 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80',
                'price' => 160000.00,
                'description' => 'Chà bông gà cay, trứng muối bùi béo phủ sốt phô mai kim sa tan chảy',
                'is_available' => true,
            ],
            [
                'category_id' => 4,
                'dish_name' => 'Bánh Kem Black Forest Socola Anh Đào',
                'image_url' => 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=600&auto=format&fit=crop&q=80',
                'price' => 340000.00,
                'description' => 'Bánh rừng đen truyền thống nước Đức với rượu anh đào và socola bào phủ kín',
                'is_available' => true,
            ],
            [
                'category_id' => 4,
                'dish_name' => 'Bánh Mousse Xoài Dừa Nhiệt Đới',
                'image_url' => 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop&q=80',
                'price' => 270000.00,
                'description' => 'Lớp thạch xoài dẻo tươi quyện mousse cốt dừa béo thơm mềm mịn',
                'is_available' => true,
            ],

            // ==========================================
            // 5. TRÁNG MIỆNG (category_id = 5) - 12 món
            // ==========================================
            [
                'category_id' => 5,
                'dish_name' => 'Chè Khúc Bạch Hạnh Nhân Thanh Mát',
                'image_url' => 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&auto=format&fit=crop&q=80',
                'price' => 35000.00,
                'description' => 'Khúc bạch phô mai dẻo béo, nhãn lồng mọng nước, hạnh nhân lát nướng giòn',
                'is_available' => true,
            ],
            [
                'category_id' => 5,
                'dish_name' => 'Chè Thái Sầu Riêng Thập Cẩm',
                'image_url' => 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
                'price' => 38000.00,
                'description' => 'Sầu riêng tươi thơm nức, mít thái, hạt lựu, thạch dừa và nước cốt dừa béo ngậy',
                'is_available' => true,
            ],
            [
                'category_id' => 5,
                'dish_name' => 'Chè Đậu Đỏ Nước Cốt Dừa',
                'image_url' => 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop&q=80',
                'price' => 28000.00,
                'description' => 'Đậu đỏ ninh nhừ bùi ngọt chan cốt dừa béo bùi mang lại nhiều may mắn',
                'is_available' => true,
            ],
            [
                'category_id' => 5,
                'dish_name' => 'Bánh Flan Caramel Truyền Thống',
                'image_url' => 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop&q=80',
                'price' => 22000.00,
                'description' => 'Bánh flan trứng sữa mềm mịn tan ngay đầu lưỡi đượm sốt caramel đăng đắng ngọt ngào',
                'is_available' => true,
            ],
            [
                'category_id' => 5,
                'dish_name' => 'Bánh Flan Sốt Cà Phê Sữa Đá',
                'image_url' => 'https://images.unsplash.com/photo-1528975604071-b4dc52a2d18c?w=600&auto=format&fit=crop&q=80',
                'price' => 25000.00,
                'description' => 'Đôi bánh flan mềm béo chan ngập cà phê pha phin thơm lừng và đá nhuyễn',
                'is_available' => true,
            ],
            [
                'category_id' => 5,
                'dish_name' => 'Pudding Trứng Sữa Trân Châu Đường Đen',
                'image_url' => 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
                'price' => 30000.00,
                'description' => 'Pudding sữa mềm núng nính kèm trân châu đường đen dẻo dai',
                'is_available' => true,
            ],
            [
                'category_id' => 5,
                'dish_name' => 'Bánh Mochi Kem Lạnh Dâu Tây (2 Viên)',
                'image_url' => 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&auto=format&fit=crop&q=80',
                'price' => 32000.00,
                'description' => 'Vỏ mochi dẻo mềm bọc nhân kem dâu mát lạnh sảng khoái',
                'is_available' => true,
            ],
            [
                'category_id' => 5,
                'dish_name' => 'Sữa Chua Dẻo Trái Cây Thập Cẩm',
                'image_url' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop&q=80',
                'price' => 35000.00,
                'description' => 'Sữa chua dẻo xắt miếng ăn kèm dâu, xoài, thanh long và sốt chanh dây',
                'is_available' => true,
            ],
            [
                'category_id' => 5,
                'dish_name' => 'Kem Vani Madagascar 2 Viên',
                'image_url' => 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=600&auto=format&fit=crop&q=80',
                'price' => 29000.00,
                'description' => 'Kem vani nguyên chất béo ngậy ăn kèm ốc quế giòn rụm',
                'is_available' => true,
            ],
            [
                'category_id' => 5,
                'dish_name' => 'Kem Chocolate Đậm Đà Bỉ',
                'image_url' => 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&auto=format&fit=crop&q=80',
                'price' => 32000.00,
                'description' => 'Kem socola Bỉ đậm vị đắng ngọt rắc vụn hạt phỉ nướng thơm',
                'is_available' => true,
            ],
            [
                'category_id' => 5,
                'dish_name' => 'Tiramisu Ly Mini Chuẩn Ý',
                'image_url' => 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&auto=format&fit=crop&q=80',
                'price' => 35000.00,
                'description' => 'Phần bánh tiramisu nhỏ xinh tiện lợi đậm vị cà phê và mascarpone',
                'is_available' => true,
            ],
            [
                'category_id' => 5,
                'dish_name' => 'Panna Cotta Dâu Tây Sốt Đỏ',
                'image_url' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop&q=80',
                'price' => 32000.00,
                'description' => 'Panna cotta mềm mướt béo thơm phủ lớp sốt dâu tây chua thanh tươi mới',
                'is_available' => true,
            ],

            // ==========================================
            // 6. PIZZA/BURGER (category_id = 6) - 12 món
            // ==========================================
            [
                'category_id' => 6,
                'dish_name' => 'Pizza Hải Sản Sốt Pesto (Size M)',
                'image_url' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80',
                'price' => 189000.00,
                'description' => 'Tôm tươi, mực ống giòn, thanh cua trên nền sốt lá quế tây Pesto và phô mai Mozzarella',
                'is_available' => true,
            ],
            [
                'category_id' => 6,
                'dish_name' => 'Pizza Bò Nướng BBQ Phô Mai',
                'image_url' => 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
                'price' => 179000.00,
                'description' => 'Thịt bò băm ướp sốt BBQ đậm đà kết hợp ớt chuông, hành tây và phô mai béo ngậy',
                'is_available' => true,
            ],
            [
                'category_id' => 6,
                'dish_name' => 'Pizza Pepperoni Xúc Xích Ý Cay',
                'image_url' => 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&auto=format&fit=crop&q=80',
                'price' => 169000.00,
                'description' => 'Xúc xích Pepperoni cay cay phủ đầy mặt bánh cùng lớp phô mai Mozzarella béo ngậy',
                'is_available' => true,
            ],
            [
                'category_id' => 6,
                'dish_name' => 'Pizza 4 Loại Phô Mai (Four Cheese)',
                'image_url' => 'https://images.unsplash.com/photo-1573821663912-569905455b1c?w=600&auto=format&fit=crop&q=80',
                'price' => 199000.00,
                'description' => 'Sự kết hợp hoàn hảo của Mozzarella, Parmesan, Cheddar và Blue Cheese thơm béo',
                'is_available' => true,
            ],
            [
                'category_id' => 6,
                'dish_name' => 'Pizza Gà Nướng Nấm Sốt Teriyaki',
                'image_url' => 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80',
                'price' => 165000.00,
                'description' => 'Thịt gà nướng mềm mọng cùng nấm tươi trên nền sốt Teriyaki ngọt thanh',
                'is_available' => true,
            ],
            [
                'category_id' => 6,
                'dish_name' => 'Pizza Xúc Xích Phô Mai Viền Phô Mai',
                'image_url' => 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=600&auto=format&fit=crop&q=80',
                'price' => 175000.00,
                'description' => 'Bánh pizza xúc xích truyền thống nâng cấp viền bánh nhồi phô mai kéo sợi',
                'is_available' => true,
            ],
            [
                'category_id' => 6,
                'dish_name' => 'Burger Bò Phô Mai Cheddar Cổ Điển',
                'image_url' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
                'price' => 65000.00,
                'description' => 'Bò nướng thơm mọng, phô mai Cheddar chảy, xà lách, cà chua và sốt đặc biệt',
                'is_available' => true,
            ],
            [
                'category_id' => 6,
                'dish_name' => 'Burger Bò BBQ Hành Tây Chiên Giòn',
                'image_url' => 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&auto=format&fit=crop&q=80',
                'price' => 72000.00,
                'description' => 'Thịt bò nướng than sốt BBQ khói kèm vòng hành tây chiên xù giòn tan',
                'is_available' => true,
            ],
            [
                'category_id' => 6,
                'dish_name' => 'Burger Gà Giòn Sốt Cay Hàn Quốc',
                'image_url' => 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&auto=format&fit=crop&q=80',
                'price' => 59000.00,
                'description' => 'Phi-lê ức gà chiên giòn tan áo sốt cay ngọt Hàn Quốc và bắp cải tím muối',
                'is_available' => true,
            ],
            [
                'category_id' => 6,
                'dish_name' => 'Burger Phi-lê Cá Hồi Sốt Tartar',
                'image_url' => 'https://images.unsplash.com/photo-1583032015879-c637a91176b6?w=600&auto=format&fit=crop&q=80',
                'price' => 75000.00,
                'description' => 'Miếng cá hồi chiên vàng giòn quyện sốt bơ Tartar thơm mát thảo mộc',
                'is_available' => true,
            ],
            [
                'category_id' => 6,
                'dish_name' => 'Burger Bò Double Cheese (2 Tầng Thịt)',
                'image_url' => 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=600&auto=format&fit=crop&q=80',
                'price' => 89000.00,
                'description' => 'Gấp đôi thịt bò nướng thơm ngậy và 2 lát phô mai Cheddar tan chảy đầy đặn',
                'is_available' => true,
            ],
            [
                'category_id' => 6,
                'dish_name' => 'Burger Tôm Giòn Sốt Mayonnaise Trứng',
                'image_url' => 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=600&auto=format&fit=crop&q=80',
                'price' => 69000.00,
                'description' => 'Nhân tôm tươi nguyên con chiên xù vàng ươm chấm sốt bơ trứng béo ngậy',
                'is_available' => true,
            ],

            // ==========================================
            // 7. MÓN LẨU (category_id = 7) - 11 món
            // ==========================================
            [
                'category_id' => 7,
                'dish_name' => 'Lẩu Thái Hải Sản Chua Cay (Set 2-3 Người)',
                'image_url' => 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop&q=80',
                'price' => 299000.00,
                'description' => 'Tôm sú, mực tươi, nghêu, bò Mỹ, nấm kim châm và nước lẩu Tomyum chuẩn vị Thái',
                'is_available' => true,
            ],
            [
                'category_id' => 7,
                'dish_name' => 'Lẩu Bò Ba Chỉ Nhúng Dấm Thanh Mát',
                'image_url' => 'https://images.unsplash.com/photo-1555126634-323283e090fa?w=600&auto=format&fit=crop&q=80',
                'price' => 329000.00,
                'description' => 'Thịt bò Mỹ mềm thơm nhúng nước dấm nước dừa tươi ăn kèm bánh tráng và mắm nêm',
                'is_available' => true,
            ],
            [
                'category_id' => 7,
                'dish_name' => 'Lẩu Gà Lá É Đặc Sản Phú Yên',
                'image_url' => 'https://images.unsplash.com/photo-1548946526-f69e2424cf45?w=600&auto=format&fit=crop&q=80',
                'price' => 279000.00,
                'description' => 'Thịt gà ta thả vườn dai ngọt nấu cùng măng le và đĩa lá é cay the thơm nức mũi',
                'is_available' => true,
            ],
            [
                'category_id' => 7,
                'dish_name' => 'Lẩu Nấm Hoàng Gia Thanh Đạm',
                'image_url' => 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80',
                'price' => 269000.00,
                'description' => 'Hơn 8 loại nấm quý: đông trùng, nấm tùng nhung, nấm tiên, nấm hương ngọt thanh bổ dưỡng',
                'is_available' => true,
            ],
            [
                'category_id' => 7,
                'dish_name' => 'Lẩu Kim Chi Hải Sản Hàn Quốc',
                'image_url' => 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80',
                'price' => 289000.00,
                'description' => 'Kim chi cải thảo giòn cay nấu cùng bạch tuộc, ba chỉ bò, đậu hũ non và mì Hàn',
                'is_available' => true,
            ],
            [
                'category_id' => 7,
                'dish_name' => 'Lẩu Cá Hồi Nấu Măng Chua',
                'image_url' => 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
                'price' => 319000.00,
                'description' => 'Đầu và lườn cá hồi béo ngậy nấu măng chua giòn, cà chua và rau thì là thơm lừng',
                'is_available' => true,
            ],
            [
                'category_id' => 7,
                'dish_name' => 'Lẩu Dê Hầm Thuốc Bắc Dinh Dưỡng',
                'image_url' => 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
                'price' => 389000.00,
                'description' => 'Thịt dê núi ướp kỹ hầm cùng táo đỏ, kỷ tử, ngải cứu và củ sen bồi bổ sức khỏe',
                'is_available' => true,
            ],
            [
                'category_id' => 7,
                'dish_name' => 'Lẩu Thập Cẩm Hải Sản & Thịt Bò',
                'image_url' => 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop&q=80',
                'price' => 349000.00,
                'description' => 'Mẹt đầy đặn tôm, mực, bò Mỹ, sườn sụn, chả viên và đĩa rau xanh theo mùa',
                'is_available' => true,
            ],
            [
                'category_id' => 7,
                'dish_name' => 'Lẩu Cua Đồng Bắp Bò Sườn Sụn',
                'image_url' => 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&auto=format&fit=crop&q=80',
                'price' => 339000.00,
                'description' => 'Gạch cua đồng thơm ngậy nấu mẻ chua thanh nhúng bắp bò hoa và sườn non sần sật',
                'is_available' => true,
            ],
            [
                'category_id' => 7,
                'dish_name' => 'Lẩu Ếch Măng Cay Đậm Vị',
                'image_url' => 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80',
                'price' => 269000.00,
                'description' => 'Thịt đùi ếch đồng xào săn cùng măng chua và ớt cay nồng đậm đà khó cưỡng',
                'is_available' => true,
            ],
            [
                'category_id' => 7,
                'dish_name' => 'Lẩu Riêu Cua Hoa Chuối Đồng Quê',
                'image_url' => 'https://images.unsplash.com/photo-1548946526-f69e2424cf45?w=600&auto=format&fit=crop&q=80',
                'price' => 299000.00,
                'description' => 'Nước dùng riêu cua giấm bỗng chua dịu ăn kèm hoa chuối bào và đậu hũ rán',
                'is_available' => true,
            ],

            // ==========================================
            // 8. SUSHI (category_id = 8) - 12 món
            // ==========================================
            [
                'category_id' => 8,
                'dish_name' => 'Sushi Cá Hồi Nauy Tươi (Sake Nigiri - 2 Miếng)',
                'image_url' => 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&auto=format&fit=crop&q=80',
                'price' => 69000.00,
                'description' => 'Cá hồi tươi Nauy nhập khẩu béo ngậy đặt trên nắm cơm giấm dẻo chuẩn Nhật',
                'is_available' => true,
            ],
            [
                'category_id' => 8,
                'dish_name' => 'Sushi Cá Ngừ Đại Dương (Maguro Nigiri - 2 Miếng)',
                'image_url' => 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=600&auto=format&fit=crop&q=80',
                'price' => 75000.00,
                'description' => 'Thịt cá ngừ đỏ au ngọt đậm đà chấm nước tương Nhật và wasabi cay nồng',
                'is_available' => true,
            ],
            [
                'category_id' => 8,
                'dish_name' => 'Sushi Tôm Sú Luộc (Ebi Nigiri - 2 Miếng)',
                'image_url' => 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=600&auto=format&fit=crop&q=80',
                'price' => 59000.00,
                'description' => 'Tôm sú tươi xẻ bướm ngọt thịt kết hợp cơm dẻo chua thanh',
                'is_available' => true,
            ],
            [
                'category_id' => 8,
                'dish_name' => 'Sushi Thanh Cua Nhật (Kani Nigiri - 2 Miếng)',
                'image_url' => 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=600&auto=format&fit=crop&q=80',
                'price' => 45000.00,
                'description' => 'Thanh cua mềm ngọt quấn rong biển nướng giòn thơm',
                'is_available' => true,
            ],
            [
                'category_id' => 8,
                'dish_name' => 'Sushi Trứng Cuộn Nhật Bản (Tamago Nigiri)',
                'image_url' => 'https://images.unsplash.com/photo-1583623025817-d180a2221d0a?w=600&auto=format&fit=crop&q=80',
                'price' => 39000.00,
                'description' => 'Trứng rán nhiều lớp ngọt thơm vị dashi truyền thống',
                'is_available' => true,
            ],
            [
                'category_id' => 8,
                'dish_name' => 'Sushi Lươn Nhật Nướng Sốt Kabayaki (Unagi)',
                'image_url' => 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80',
                'price' => 89000.00,
                'description' => 'Lươn Nhật nướng than hoa mềm tan đẫm nước sốt tương ngọt sánh mịn',
                'is_available' => true,
            ],
            [
                'category_id' => 8,
                'dish_name' => 'Sushi Bơ Trái Xanh Tươi (Avocado Nigiri)',
                'image_url' => 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
                'price' => 42000.00,
                'description' => 'Bơ sáp béo ngậy thái lát thanh mát tốt cho sức khỏe',
                'is_available' => true,
            ],
            [
                'category_id' => 8,
                'dish_name' => 'California Roll Cuộn Trứng Cua Tobiko (6 Miếng)',
                'image_url' => 'https://images.unsplash.com/photo-1617196034096-787140f7b5bc?w=600&auto=format&fit=crop&q=80',
                'price' => 85000.00,
                'description' => 'Cơm cuộn thanh cua, bơ sáp, dưa leo phủ đầy trứng cua tobiko cam giòn tí tách',
                'is_available' => true,
            ],
            [
                'category_id' => 8,
                'dish_name' => 'Salmon Roll Cá Hồi Sốt Cay (6 Miếng)',
                'image_url' => 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&auto=format&fit=crop&q=80',
                'price' => 95000.00,
                'description' => 'Cá hồi tươi cuộn sốt cay spicy mayo và hành lá thơm nức',
                'is_available' => true,
            ],
            [
                'category_id' => 8,
                'dish_name' => 'Tempura Roll Tôm Chiên Giòn Rụm (6 Miếng)',
                'image_url' => 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=600&auto=format&fit=crop&q=80',
                'price' => 89000.00,
                'description' => 'Tôm chiên xù tempura giòn rụm cuộn cùng sốt mè rang béo ngậy',
                'is_available' => true,
            ],
            [
                'category_id' => 8,
                'dish_name' => 'Maki Cá Hồi Cuộn Rong Biển (6 Miếng)',
                'image_url' => 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=600&auto=format&fit=crop&q=80',
                'price' => 65000.00,
                'description' => 'Cuộn rong biển nhỏ xinh nhân cá hồi tươi ngon miệng',
                'is_available' => true,
            ],
            [
                'category_id' => 8,
                'dish_name' => 'Set Sushi Tổng Hợp Premium (12 Miếng Đủ Loại)',
                'image_url' => 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&auto=format&fit=crop&q=80',
                'price' => 219000.00,
                'description' => 'Gồm 4 Nigiri cá hồi, 2 cá ngừ, 2 tôm, 2 lươn nướng và 2 thanh cua cao cấp',
                'is_available' => true,
            ],

            // ==========================================
            // 9. MÌ PHỞ (category_id = 9) - 12 món
            // ==========================================
            [
                'category_id' => 9,
                'dish_name' => 'Phở Bò Tái Nạm Gầu Đặc Biệt',
                'image_url' => 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&auto=format&fit=crop&q=80',
                'price' => 55000.00,
                'description' => 'Nước dùng ninh xương bò 12 tiếng thơm quế hồi cùng thịt bò tái mềm và nạm giòn',
                'is_available' => true,
            ],
            [
                'category_id' => 9,
                'dish_name' => 'Phở Bò Viên Nước Dùng Đậm Đà',
                'image_url' => 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80',
                'price' => 48000.00,
                'description' => 'Bò viên gân giòn sần sật chấm tương đen ớt sa tế cùng nước phở thanh ngọt',
                'is_available' => true,
            ],
            [
                'category_id' => 9,
                'dish_name' => 'Phở Gà Ta Thịt Xé Lá Chanh',
                'image_url' => 'https://images.unsplash.com/photo-1548946526-f69e2424cf45?w=600&auto=format&fit=crop&q=80',
                'price' => 50000.00,
                'description' => 'Gà ta da giòn thịt ngọt xé miếng rắc lá chanh non thái chỉ thơm ngát',
                'is_available' => true,
            ],
            [
                'category_id' => 9,
                'dish_name' => 'Phở Bò Tái Lăn Áp Chảo Thơm Lừng',
                'image_url' => 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&auto=format&fit=crop&q=80',
                'price' => 59000.00,
                'description' => 'Thịt bò xào lăn tỏi lửa lớn dậy mùi khói thơm lừng chan nước dùng béo ngậy',
                'is_available' => true,
            ],
            [
                'category_id' => 9,
                'dish_name' => 'Mì Bò Sốt Cay Sa Tế',
                'image_url' => 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80',
                'price' => 52000.00,
                'description' => 'Sợi mì trứng tươi dai vàng óng cùng thịt bắp bò mềm sốt sa tế cay nồng',
                'is_available' => true,
            ],
            [
                'category_id' => 9,
                'dish_name' => 'Mì Gà Quay Xá Xíu Da Giòn Rụm',
                'image_url' => 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=600&auto=format&fit=crop&q=80',
                'price' => 55000.00,
                'description' => 'Đùi gà quay mật ong vàng ươm và thịt xá xíu sốt tương đậm đà',
                'is_available' => true,
            ],
            [
                'category_id' => 9,
                'dish_name' => 'Mì Hải Sản Tôm Mực Cay Nồng',
                'image_url' => 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&auto=format&fit=crop&q=80',
                'price' => 59000.00,
                'description' => 'Tôm sú tươi bóc nõn, mực ống giòn sần sật trong nước dùng hải sản đậm đà',
                'is_available' => true,
            ],
            [
                'category_id' => 9,
                'dish_name' => 'Mì Xào Bò Rau Cải Ngọt',
                'image_url' => 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
                'price' => 49000.00,
                'description' => 'Mì xào mềm thấm gia vị cùng thịt thăn bò xào tái và cải thìa xanh giòn',
                'is_available' => true,
            ],
            [
                'category_id' => 9,
                'dish_name' => 'Mì Xào Giòn Hải Sản Thập Cẩm',
                'image_url' => 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=600&auto=format&fit=crop&q=80',
                'price' => 55000.00,
                'description' => 'Vắt mì chiên giòn rụm ngập trong sốt sệt hải sản tôm mực rau củ',
                'is_available' => true,
            ],
            [
                'category_id' => 9,
                'dish_name' => 'Hủ Tiếu Nam Vang Sườn Tôm Trứng Cút',
                'image_url' => 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80',
                'price' => 50000.00,
                'description' => 'Sợi hủ tiếu dai tôm tươi, thịt nạc băm, sườn non và tỏi phi thơm phức',
                'is_available' => true,
            ],
            [
                'category_id' => 9,
                'dish_name' => 'Bún Bò Huế Chả Cua Giò Heo',
                'image_url' => 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&auto=format&fit=crop&q=80',
                'price' => 55000.00,
                'description' => 'Sợi bún to trong nước dùng thơm mùi sả mắm ruốc cùng khoanh giò heo béo ngậy',
                'is_available' => true,
            ],
            [
                'category_id' => 9,
                'dish_name' => 'Bún Mọc Sườn Non Dọc Mùng',
                'image_url' => 'https://images.unsplash.com/photo-1548946526-f69e2424cf45?w=600&auto=format&fit=crop&q=80',
                'price' => 48000.00,
                'description' => 'Viên mọc nấm hương thơm lừng, sườn non ninh mềm cùng dọc mùng giòn sần sật',
                'is_available' => true,
            ],

            // ==========================================
            // 10. CƠM HỘP (category_id = 10) - 12 món
            // ==========================================
            [
                'category_id' => 10,
                'dish_name' => 'Cơm Tấm Sườn Nướng Mỡ Hành Trứng Ốp',
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
                'price' => 45000.00,
                'description' => 'Miếng sườn cốt lết ướp mật ong nướng than thơm lừng, mỡ hành béo ngậy và nước mắm kẹo',
                'is_available' => true,
            ],
            [
                'category_id' => 10,
                'dish_name' => 'Cơm Đùi Gà Nướng Mật Ong Xối Mỡ',
                'image_url' => 'https://images.unsplash.com/photo-1527477321005-4d01d75c2e55?w=600&auto=format&fit=crop&q=80',
                'price' => 45000.00,
                'description' => 'Góc tư đùi gà nướng mật ong da vàng óng mọng nước ăn kèm dưa chua thanh mát',
                'is_available' => true,
            ],
            [
                'category_id' => 10,
                'dish_name' => 'Cơm Cánh Gà Chiên Nước Mắm Tỏi Ớt',
                'image_url' => 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600&auto=format&fit=crop&q=80',
                'price' => 42000.00,
                'description' => 'Cánh gà chiên giòn thấm đẫm sốt mắm kẹo tỏi ớt đưa cơm cực đỉnh',
                'is_available' => true,
            ],
            [
                'category_id' => 10,
                'dish_name' => 'Cơm Bò Lúc Lắc Khoai Tây Chiên',
                'image_url' => 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
                'price' => 59000.00,
                'description' => 'Thăn bò mềm xào bơ tỏi ớt chuông ăn cùng cơm trắng nóng hổi',
                'is_available' => true,
            ],
            [
                'category_id' => 10,
                'dish_name' => 'Cơm Thịt Kho Tàu Trứng Cút Đậm Đà',
                'image_url' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop&q=80',
                'price' => 42000.00,
                'description' => 'Thịt ba chỉ kho nước dừa mềm tan cùng trứng cút bùi bùi chuẩn cơm mẹ nấu',
                'is_available' => true,
            ],
            [
                'category_id' => 10,
                'dish_name' => 'Cơm Cá Basa Phi Lê Chiên Sốt Cà Chua',
                'image_url' => 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
                'price' => 40000.00,
                'description' => 'Phi lê cá basa chiên vàng giòn rưới sốt cà chua tươi thì là thơm nức',
                'is_available' => true,
            ],
            [
                'category_id' => 10,
                'dish_name' => 'Cơm Cá Lóc Kho Tộ Tiêu Ớt',
                'image_url' => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
                'price' => 42000.00,
                'description' => 'Cá lóc đồng kho tộ keo quánh đậm đà ăn kèm dưa leo rau sống',
                'is_available' => true,
            ],
            [
                'category_id' => 10,
                'dish_name' => 'Cơm Xá Xíu Mật Ong Quảng Đông',
                'image_url' => 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&auto=format&fit=crop&q=80',
                'price' => 48000.00,
                'description' => 'Thịt nạc vai ướp sốt xá xíu mật ong nướng mềm thơm đỏ hồng bắt mắt',
                'is_available' => true,
            ],
            [
                'category_id' => 10,
                'dish_name' => 'Cơm Ba Chỉ Nướng Kim Chi Hàn Quốc',
                'image_url' => 'https://images.unsplash.com/photo-1558030006-450675393462?w=600&auto=format&fit=crop&q=80',
                'price' => 45000.00,
                'description' => 'Thịt ba rọi nướng cháy cạnh xém vàng ăn kèm kim chi cay giòn chống ngấy',
                'is_available' => true,
            ],
            [
                'category_id' => 10,
                'dish_name' => 'Cơm Gà Sốt Cay Phô Mai Kéo Sợi',
                'image_url' => 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=600&auto=format&fit=crop&q=80',
                'price' => 49000.00,
                'description' => 'Gà rút xương xào sốt cay cay phủ lớp phô mai nướng chảy béo ngậy',
                'is_available' => true,
            ],
            [
                'category_id' => 10,
                'dish_name' => 'Cơm Bò Bít Tết Sốt Tiêu Đen Trứng Ốp',
                'image_url' => 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
                'price' => 62000.00,
                'description' => 'Bò bít tết thăn mềm rưới sốt tiêu đen cay nồng kèm trứng ốp lòng đào',
                'is_available' => true,
            ],
            [
                'category_id' => 10,
                'dish_name' => 'Cơm Cá Hồi Sốt Teriyaki Dinh Dưỡng',
                'image_url' => 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
                'price' => 79000.00,
                'description' => 'Phi lê cá hồi Nauy áp chảo sốt Teriyaki Nhật Bản giàu Omega-3 tốt cho sức khỏe',
                'is_available' => true,
            ],
        ];

        foreach ($dishes as $dishData) {
            Dish::updateOrCreate(
                [
                    'dish_name' => $dishData['dish_name'],
                    'category_id' => $dishData['category_id']
                ],
                $dishData
            );
        }
    }
}
